/*
 * API Hub'Eau - Ecoulement des cours d'eau
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: vbeta
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HubEauKit.Api;
using HubEauKit.Model;
using HubEauKit.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace HubEauKit.Test.Model
{
    /// <summary>
    ///  Class for testing CampagneResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CampagneResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CampagneResult
        //private CampagneResult instance;

        public CampagneResultTests()
        {
            // TODO uncomment below to create an instance of CampagneResult
            //instance = new CampagneResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CampagneResult
        /// </summary>
        [Fact]
        public void CampagneResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" CampagneResult
            //Assert.IsType<CampagneResult>(instance);
        }


        /// <summary>
        /// Test the property 'Count'
        /// </summary>
        [Fact]
        public void CountTest()
        {
            // TODO unit test for the property 'Count'
        }
        /// <summary>
        /// Test the property 'First'
        /// </summary>
        [Fact]
        public void FirstTest()
        {
            // TODO unit test for the property 'First'
        }
        /// <summary>
        /// Test the property 'Last'
        /// </summary>
        [Fact]
        public void LastTest()
        {
            // TODO unit test for the property 'Last'
        }
        /// <summary>
        /// Test the property 'Prev'
        /// </summary>
        [Fact]
        public void PrevTest()
        {
            // TODO unit test for the property 'Prev'
        }
        /// <summary>
        /// Test the property 'Next'
        /// </summary>
        [Fact]
        public void NextTest()
        {
            // TODO unit test for the property 'Next'
        }
        /// <summary>
        /// Test the property 'ApiVersion'
        /// </summary>
        [Fact]
        public void ApiVersionTest()
        {
            // TODO unit test for the property 'ApiVersion'
        }
        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }

    }

}
