/*
 * API Hub'Eau - Ecoulement des cours d'eau
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: vbeta
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HubEauKit.Api;
using HubEauKit.Model;
using HubEauKit.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace HubEauKit.Test.Model
{
    /// <summary>
    ///  Class for testing Campagne
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CampagneTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Campagne
        //private Campagne instance;

        public CampagneTests()
        {
            // TODO uncomment below to create an instance of Campagne
            //instance = new Campagne();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Campagne
        /// </summary>
        [Fact]
        public void CampagneInstanceTest()
        {
            // TODO uncomment below to test "IsType" Campagne
            //Assert.IsType<Campagne>(instance);
        }


        /// <summary>
        /// Test the property 'CodeCampagne'
        /// </summary>
        [Fact]
        public void CodeCampagneTest()
        {
            // TODO unit test for the property 'CodeCampagne'
        }
        /// <summary>
        /// Test the property 'DateCampagne'
        /// </summary>
        [Fact]
        public void DateCampagneTest()
        {
            // TODO unit test for the property 'DateCampagne'
        }
        /// <summary>
        /// Test the property 'NombreModaliteEcoulement'
        /// </summary>
        [Fact]
        public void NombreModaliteEcoulementTest()
        {
            // TODO unit test for the property 'NombreModaliteEcoulement'
        }
        /// <summary>
        /// Test the property 'CodeTypeCampagne'
        /// </summary>
        [Fact]
        public void CodeTypeCampagneTest()
        {
            // TODO unit test for the property 'CodeTypeCampagne'
        }
        /// <summary>
        /// Test the property 'LibelleTypeCampagne'
        /// </summary>
        [Fact]
        public void LibelleTypeCampagneTest()
        {
            // TODO unit test for the property 'LibelleTypeCampagne'
        }
        /// <summary>
        /// Test the property 'CodeReseau'
        /// </summary>
        [Fact]
        public void CodeReseauTest()
        {
            // TODO unit test for the property 'CodeReseau'
        }
        /// <summary>
        /// Test the property 'LibelleReseau'
        /// </summary>
        [Fact]
        public void LibelleReseauTest()
        {
            // TODO unit test for the property 'LibelleReseau'
        }
        /// <summary>
        /// Test the property 'UriReseau'
        /// </summary>
        [Fact]
        public void UriReseauTest()
        {
            // TODO unit test for the property 'UriReseau'
        }
        /// <summary>
        /// Test the property 'CodeDepartement'
        /// </summary>
        [Fact]
        public void CodeDepartementTest()
        {
            // TODO unit test for the property 'CodeDepartement'
        }
        /// <summary>
        /// Test the property 'LibelleDepartement'
        /// </summary>
        [Fact]
        public void LibelleDepartementTest()
        {
            // TODO unit test for the property 'LibelleDepartement'
        }

    }

}
