/*
 * API Hub'Eau - Ecoulement des cours d'eau
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: vbeta
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HubEauKit.Api;
using HubEauKit.Model;
using HubEauKit.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace HubEauKit.Test.Model
{
    /// <summary>
    ///  Class for testing Observation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ObservationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Observation
        //private Observation instance;

        public ObservationTests()
        {
            // TODO uncomment below to create an instance of Observation
            //instance = new Observation();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Observation
        /// </summary>
        [Fact]
        public void ObservationInstanceTest()
        {
            // TODO uncomment below to test "IsType" Observation
            //Assert.IsType<Observation>(instance);
        }


        /// <summary>
        /// Test the property 'CodeStation'
        /// </summary>
        [Fact]
        public void CodeStationTest()
        {
            // TODO unit test for the property 'CodeStation'
        }
        /// <summary>
        /// Test the property 'LibelleStation'
        /// </summary>
        [Fact]
        public void LibelleStationTest()
        {
            // TODO unit test for the property 'LibelleStation'
        }
        /// <summary>
        /// Test the property 'UriStation'
        /// </summary>
        [Fact]
        public void UriStationTest()
        {
            // TODO unit test for the property 'UriStation'
        }
        /// <summary>
        /// Test the property 'CodeDepartement'
        /// </summary>
        [Fact]
        public void CodeDepartementTest()
        {
            // TODO unit test for the property 'CodeDepartement'
        }
        /// <summary>
        /// Test the property 'LibelleDepartement'
        /// </summary>
        [Fact]
        public void LibelleDepartementTest()
        {
            // TODO unit test for the property 'LibelleDepartement'
        }
        /// <summary>
        /// Test the property 'CodeCommune'
        /// </summary>
        [Fact]
        public void CodeCommuneTest()
        {
            // TODO unit test for the property 'CodeCommune'
        }
        /// <summary>
        /// Test the property 'LibelleCommune'
        /// </summary>
        [Fact]
        public void LibelleCommuneTest()
        {
            // TODO unit test for the property 'LibelleCommune'
        }
        /// <summary>
        /// Test the property 'CodeRegion'
        /// </summary>
        [Fact]
        public void CodeRegionTest()
        {
            // TODO unit test for the property 'CodeRegion'
        }
        /// <summary>
        /// Test the property 'LibelleRegion'
        /// </summary>
        [Fact]
        public void LibelleRegionTest()
        {
            // TODO unit test for the property 'LibelleRegion'
        }
        /// <summary>
        /// Test the property 'CodeBassin'
        /// </summary>
        [Fact]
        public void CodeBassinTest()
        {
            // TODO unit test for the property 'CodeBassin'
        }
        /// <summary>
        /// Test the property 'LibelleBassin'
        /// </summary>
        [Fact]
        public void LibelleBassinTest()
        {
            // TODO unit test for the property 'LibelleBassin'
        }
        /// <summary>
        /// Test the property 'CoordonneeXStation'
        /// </summary>
        [Fact]
        public void CoordonneeXStationTest()
        {
            // TODO unit test for the property 'CoordonneeXStation'
        }
        /// <summary>
        /// Test the property 'CoordonneeYStation'
        /// </summary>
        [Fact]
        public void CoordonneeYStationTest()
        {
            // TODO unit test for the property 'CoordonneeYStation'
        }
        /// <summary>
        /// Test the property 'CodeProjectionStation'
        /// </summary>
        [Fact]
        public void CodeProjectionStationTest()
        {
            // TODO unit test for the property 'CodeProjectionStation'
        }
        /// <summary>
        /// Test the property 'LibelleProjectionStation'
        /// </summary>
        [Fact]
        public void LibelleProjectionStationTest()
        {
            // TODO unit test for the property 'LibelleProjectionStation'
        }
        /// <summary>
        /// Test the property 'CodeCoursEau'
        /// </summary>
        [Fact]
        public void CodeCoursEauTest()
        {
            // TODO unit test for the property 'CodeCoursEau'
        }
        /// <summary>
        /// Test the property 'LibelleCoursEau'
        /// </summary>
        [Fact]
        public void LibelleCoursEauTest()
        {
            // TODO unit test for the property 'LibelleCoursEau'
        }
        /// <summary>
        /// Test the property 'UriCoursEau'
        /// </summary>
        [Fact]
        public void UriCoursEauTest()
        {
            // TODO unit test for the property 'UriCoursEau'
        }
        /// <summary>
        /// Test the property 'CodeCampagne'
        /// </summary>
        [Fact]
        public void CodeCampagneTest()
        {
            // TODO unit test for the property 'CodeCampagne'
        }
        /// <summary>
        /// Test the property 'CodeReseau'
        /// </summary>
        [Fact]
        public void CodeReseauTest()
        {
            // TODO unit test for the property 'CodeReseau'
        }
        /// <summary>
        /// Test the property 'LibelleReseau'
        /// </summary>
        [Fact]
        public void LibelleReseauTest()
        {
            // TODO unit test for the property 'LibelleReseau'
        }
        /// <summary>
        /// Test the property 'UriReseau'
        /// </summary>
        [Fact]
        public void UriReseauTest()
        {
            // TODO unit test for the property 'UriReseau'
        }
        /// <summary>
        /// Test the property 'DateObservation'
        /// </summary>
        [Fact]
        public void DateObservationTest()
        {
            // TODO unit test for the property 'DateObservation'
        }
        /// <summary>
        /// Test the property 'CodeEcoulement'
        /// </summary>
        [Fact]
        public void CodeEcoulementTest()
        {
            // TODO unit test for the property 'CodeEcoulement'
        }
        /// <summary>
        /// Test the property 'LibelleEcoulement'
        /// </summary>
        [Fact]
        public void LibelleEcoulementTest()
        {
            // TODO unit test for the property 'LibelleEcoulement'
        }
        /// <summary>
        /// Test the property 'Latitude'
        /// </summary>
        [Fact]
        public void LatitudeTest()
        {
            // TODO unit test for the property 'Latitude'
        }
        /// <summary>
        /// Test the property 'Longitude'
        /// </summary>
        [Fact]
        public void LongitudeTest()
        {
            // TODO unit test for the property 'Longitude'
        }

    }

}
